To enable the debug_package in mkspec.
This patch is used to strip the debug symbols from binary
files and generating separate debug-info rpm along with
binary rpm while building the kernel.

Change-Id: Iad2cfd8e252d218a9d603e9dbed2aa557d83e263
Co-Authored by:shravani paladugula <shravani.p@tcs.com>
Signed-off-by: Navya Bathula <navyax.bathula@intel.com>

diff --git a/kernel/scripts/package/mkspec b/kernel/scripts/package/mkspec
--- a/kernel/scripts/package/mkspec
+++ b/kernel/scripts/package/mkspec
@@ -39,10 +39,14 @@ if ! $PREBUILT; then
 echo "Source: kernel-$__KERNELRELEASE.tar.gz"
 fi
 
+echo "%undefine _missing_build_ids_terminate_build"
 echo "BuildRoot: %{_tmppath}/%{name}-%{PACKAGE_VERSION}-root"
 echo "Provides: $PROVIDES"
-echo "%define __spec_install_post /usr/lib/rpm/brp-compress || :"
-echo "%define debug_package %{nil}"
+#echo "%define __spec_install_post /usr/lib/rpm/brp-compress || :"
+#echo "%define debug_package %{nil}"
+echo "%define __spec_install_post %{__os_install_post}"
+
+
 echo ""
 echo "%description"
 echo "The Linux Kernel, the operating system core itself"
