To enable the debug_package in mkspec.
This patch is used to strip the debug symbols from binary
files and generating separate debug-info rpm along with
binary rpm while building the kernel.

Change-Id: Iad2cfd8e252d218a9d603e9dbed2aa557d83e263
Co-Authored by:shravani paladugula <shravani.p@tcs.com>
Signed-off-by: Navya Bathula <navyax.bathula@intel.com>

diff --git a/kernel/scripts/package/mkspec b/kernel/scripts/package/mkspec
--- a/kernel/scripts/package/mkspec
+++ b/kernel/scripts/package/mkspec
@@ -39,10 +39,24 @@ if ! $PREBUILT; then
 echo "Source: kernel-$__KERNELRELEASE.tar.gz"
 fi
 
+echo "%undefine _missing_build_ids_terminate_build"
+echo "%define with_debug     %{?_without_debug:     0} %{?!_without_debug:     1}"
+echo "%define with_debuginfo %{?_without_debuginfo: 0} %{?!_without_debuginfo: 1}"
+echo "%define __os_install_post /usr/lib/rpm/brp-strip"
+echo "%undefine __strip"
+echo "%define debuginfo_args %{nil}"
 echo "BuildRoot: %{_tmppath}/%{name}-%{PACKAGE_VERSION}-root"
 echo "Provides: $PROVIDES"
-echo "%define __spec_install_post /usr/lib/rpm/brp-compress || :"
-echo "%define debug_package %{nil}"
+#echo "%define __spec_install_post /usr/lib/rpm/brp-compress || :"
+#echo "%define debug_package %{nil}"
+echo "%package debuginfo-common-%{_target_cpu}"
+echo "Summary: Kernel source files used by %{name}-debuginfo packages"
+echo "Group: Development/Debug"
+echo "%description debuginfo-common-%{_target_cpu}"
+echo "This package is required by %{name}-debuginfo subpackages."
+echo "It provides the kernel source files common to all builds."
+
+
 echo ""
 echo "%description"
 echo "The Linux Kernel, the operating system core itself"
@@ -80,6 +94,29 @@ if ! $PREBUILT; then
 echo "make clean && make %{?_smp_mflags}"
 echo ""
 fi
+
+echo "%define debug_package %{nil}"
+echo "%if %{with_debuginfo}"
+
+echo "%define __debug_install_post \\"
+echo "/usr/lib/rpm/find-debuginfo.sh %{debuginfo_args} %{_builddir}/%{?buildsubdir}\\"
+echo "%{nil}"
+
+echo "%ifnarch noarch"
+echo "%global __debug_package 1"
+echo "%files -f debugfiles.list debuginfo-common-%{_target_cpu}"
+echo "%defattr(-,root,root)"
+echo "%endif"
+
+echo "%endif"
+
+
+echo "%define __spec_install_post \\"
+echo " %{?__debug_package:%{__debug_install_post}}\\"
+echo " %{__os_install_post}"
+
+echo ""
+
 
 echo "%install"
 echo 'KBUILD_IMAGE=$(make image_name)'
